name: toridori_grinder_tasks
description: A starting point for Dart libraries or applications.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: "^3.0.0"

dependencies:
  github: ^9.17.0
  grinder: ^0.9.4
  http: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
