name: toridori_grinder_tasks
description: A starting point for Dart libraries or applications.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  github: ^9.9.0
  grinder: ^0.9.3
  http: ^0.13.5
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
